import { z } from "zod";
import { router, publicProcedure } from "../trpc";
import * as lcs from "@/lib/integrations/lcs";
import * as engine from "@/lib/conveyancing-engine";
import { db } from "@/lib/db";

export const conveyancingRouter = router({
  // ── Settings ───────────────────────────────────────────────────────

  "settings.get": publicProcedure.query(async ({ ctx }) => {
    return ctx.db.conveyancingIntegration.findUnique({ where: { provider: "LCS" } });
  }),

  "settings.update": publicProcedure
    .input(z.object({
      isEnabled: z.boolean().optional(),
      apiKey: z.string().optional(),
      apiSecret: z.string().optional(),
      baseUrl: z.string().optional(),
      accountId: z.string().optional(),
      firmId: z.string().optional(),
      webhookUrl: z.string().optional(),
      webhookSecret: z.string().optional(),
      autoSyncMatters: z.boolean().optional(),
      autoGenerateDocuments: z.boolean().optional(),
      autoCalculateAdjustments: z.boolean().optional(),
      defaultJurisdiction: z.string().optional(),
      defaultTitleCompany: z.string().optional(),
      settings: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.conveyancingIntegration.upsert({
        where: { provider: "LCS" },
        create: { provider: "LCS", displayName: "LCS", ...input },
        update: input,
      });
    }),

  "settings.test": publicProcedure.mutation(async () => {
    return lcs.testConnection();
  }),

  // ── Matters ────────────────────────────────────────────────────────

  "matters.list": publicProcedure
    .input(z.object({
      transactionType: z.string().optional(),
      status: z.string().optional(),
      role: z.string().optional(),
      closingDateFrom: z.date().optional(),
      closingDateTo: z.date().optional(),
      propertyAddress: z.string().optional(),
      clientId: z.string().optional(),
      orderBy: z.enum(["closingDate", "createdAt"]).optional(),
    }).optional())
    .query(async ({ ctx, input }) => {
      return ctx.db.conveyancingMatter.findMany({
        where: {
          ...(input?.transactionType && { transactionType: input.transactionType as any }),
          ...(input?.status && { status: input.status as any }),
          ...(input?.role && { role: input.role as any }),
          ...(input?.clientId && { clientId: input.clientId }),
          ...(input?.propertyAddress && { propertyAddress: { contains: input.propertyAddress } }),
          ...((input?.closingDateFrom || input?.closingDateTo) && {
            closingDate: {
              ...(input?.closingDateFrom && { gte: input.closingDateFrom }),
              ...(input?.closingDateTo && { lte: input.closingDateTo }),
            },
          }),
        },
        include: { matter: true },
        orderBy: { [input?.orderBy || "createdAt"]: "desc" },
      });
    }),

  "matters.get": publicProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.conveyancingMatter.findUniqueOrThrow({
        where: { id: input.id },
        include: { checklists: true, adjustments: true, statements: true, titleExceptions: true, activities: true, matter: true },
      });
    }),

  "matters.create": publicProcedure
    .input(z.object({
      matterId: z.string(),
      clientId: z.string(),
      transactionType: z.string(),
      propertyAddress: z.string(),
      salePrice: z.number().optional(),
      closingDate: z.string().optional(),
      buyerName: z.string().optional(),
      sellerName: z.string().optional(),
      notes: z.string().optional(),
    }).passthrough())
    .mutation(async ({ input }) => {
      return engine.createConveyancingMatter(input);
    }),

  "matters.update": publicProcedure
    .input(z.object({ id: z.string(), data: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.conveyancingMatter.update({ where: { id: input.id }, data: input.data as any });
    }),

  "matters.delete": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.conveyancingMatter.delete({ where: { id: input.id } });
    }),

  "matters.syncToLCS": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const matter = await ctx.db.conveyancingMatter.findUniqueOrThrow({ where: { id: input.id } });
      if (matter.externalMatterId) {
        return lcs.updateMatter(matter.externalMatterId, matter);
      }
      return lcs.createMatter(matter);
    }),

  "matters.syncFromLCS": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const matter = await ctx.db.conveyancingMatter.findUniqueOrThrow({ where: { id: input.id } });
      if (!matter.externalMatterId) throw new Error("No external matter ID");
      const result = await lcs.getMatter(matter.externalMatterId);
      if (!result.success) throw new Error(result.error);
      return ctx.db.conveyancingMatter.update({ where: { id: input.id }, data: { rawPayload: JSON.stringify(result.data) } });
    }),

  "matters.checkReadiness": publicProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ input }) => {
      return engine.checkClosingReadiness(input.id);
    }),

  "matters.postClosing": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ input }) => {
      return engine.postClosingWorkflow(input.id);
    }),

  // ── Checklist ──────────────────────────────────────────────────────

  "checklist.get": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.closingChecklist.findMany({ where: { conveyancingMatterId: input.conveyancingMatterId } });
    }),

  "checklist.generate": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .mutation(async ({ input }) => {
      return engine.generateClosingChecklist(input.conveyancingMatterId);
    }),

  "checklist.updateItem": publicProcedure
    .input(z.object({ checklistId: z.string(), itemIndex: z.number(), updates: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      const checklist = await ctx.db.closingChecklist.findUniqueOrThrow({ where: { id: input.checklistId } });
      const items = JSON.parse(checklist.items);
      items[input.itemIndex] = { ...items[input.itemIndex], ...input.updates };
      const completedCount = items.filter((i: any) => i.status === "COMPLETED").length;
      return ctx.db.closingChecklist.update({
        where: { id: input.checklistId },
        data: { items: JSON.stringify(items), completedCount, totalCount: items.length, completionPercentage: items.length > 0 ? (completedCount / items.length) * 100 : 0, lastUpdated: new Date() },
      });
    }),

  "checklist.bulkUpdate": publicProcedure
    .input(z.object({ checklistId: z.string(), updates: z.array(z.object({ itemIndex: z.number(), changes: z.record(z.unknown()) })) }))
    .mutation(async ({ ctx, input }) => {
      const checklist = await ctx.db.closingChecklist.findUniqueOrThrow({ where: { id: input.checklistId } });
      const items = JSON.parse(checklist.items);
      for (const u of input.updates) {
        items[u.itemIndex] = { ...items[u.itemIndex], ...u.changes };
      }
      const completedCount = items.filter((i: any) => i.status === "COMPLETED").length;
      return ctx.db.closingChecklist.update({
        where: { id: input.checklistId },
        data: { items: JSON.stringify(items), completedCount, totalCount: items.length, completionPercentage: items.length > 0 ? (completedCount / items.length) * 100 : 0, lastUpdated: new Date() },
      });
    }),

  "checklist.getProgress": publicProcedure
    .input(z.object({ checklistId: z.string() }))
    .query(async ({ ctx, input }) => {
      const checklist = await ctx.db.closingChecklist.findUniqueOrThrow({ where: { id: input.checklistId } });
      return { completedCount: checklist.completedCount, totalCount: checklist.totalCount, percentage: checklist.totalCount > 0 ? (checklist.completedCount / checklist.totalCount) * 100 : 0 };
    }),

  // ── Adjustments ────────────────────────────────────────────────────

  "adjustments.list": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.closingAdjustment.findMany({ where: { conveyancingMatterId: input.conveyancingMatterId }, orderBy: { createdAt: "asc" } });
    }),

  "adjustments.calculate": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string(), closingDate: z.date() }))
    .mutation(async ({ input }) => {
      return engine.calculateProrations(input.conveyancingMatterId, input.closingDate);
    }),

  "adjustments.create": publicProcedure
    .input(z.object({
      conveyancingMatterId: z.string(),
      adjustmentType: z.string(),
      description: z.string(),
      totalAmount: z.number(),
      adjustedAmount: z.number(),
      prorationType: z.string().optional(),
      prorationDate: z.date(),
      creditTo: z.string(),
      notes: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingAdjustment.create({ data: input as any });
    }),

  "adjustments.update": publicProcedure
    .input(z.object({ id: z.string(), data: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingAdjustment.update({ where: { id: input.id }, data: input.data as any });
    }),

  "adjustments.delete": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingAdjustment.delete({ where: { id: input.id } });
    }),

  "adjustments.recalculate": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string(), closingDate: z.date() }))
    .mutation(async ({ ctx, input }) => {
      await ctx.db.closingAdjustment.deleteMany({ where: { conveyancingMatterId: input.conveyancingMatterId } });
      return engine.calculateProrations(input.conveyancingMatterId, input.closingDate);
    }),

  // ── Statements ─────────────────────────────────────────────────────

  "statements.generate": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string(), statementType: z.enum(["BUYER", "SELLER"]) }))
    .mutation(async ({ input }) => {
      return engine.generateClosingStatement(input.conveyancingMatterId, input.statementType);
    }),

  "statements.get": publicProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.closingStatement.findUniqueOrThrow({ where: { id: input.id } });
    }),

  "statements.list": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.closingStatement.findMany({ where: { conveyancingMatterId: input.conveyancingMatterId }, orderBy: { createdAt: "desc" } });
    }),

  "statements.update": publicProcedure
    .input(z.object({ id: z.string(), data: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingStatement.update({ where: { id: input.id }, data: input.data as any });
    }),

  "statements.approve": publicProcedure
    .input(z.object({ id: z.string(), approvedBy: z.string() }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingStatement.update({ where: { id: input.id }, data: { status: "FINAL", approvedBy: input.approvedBy, approvedAt: new Date() } });
    }),

  "statements.export": publicProcedure
    .input(z.object({ id: z.string(), format: z.enum(["pdf", "csv", "xlsx"]).optional() }))
    .query(async ({ input }) => {
      return { message: "Export functionality coming soon", statementId: input.id, format: input.format || "pdf" };
    }),

  // ── Title ──────────────────────────────────────────────────────────

  "title.getExceptions": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.titleException.findMany({ where: { conveyancingMatterId: input.conveyancingMatterId }, orderBy: { createdAt: "desc" } });
    }),

  "title.addException": publicProcedure
    .input(z.object({
      conveyancingMatterId: z.string(),
      exceptionType: z.string(),
      description: z.string(),
      amount: z.number().optional(),
      holder: z.string().optional(),
      recordingInfo: z.string().optional(),
      filingDate: z.date().optional(),
      notes: z.string().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.titleException.create({ data: input as any });
    }),

  "title.updateException": publicProcedure
    .input(z.object({ id: z.string(), data: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.titleException.update({ where: { id: input.id }, data: input.data as any });
    }),

  "title.clearException": publicProcedure
    .input(z.object({ exceptionId: z.string(), clearedBy: z.string(), clearanceMethod: z.string(), notes: z.string().optional() }))
    .mutation(async ({ input }) => {
      return engine.clearTitleException(input.exceptionId, { clearedBy: input.clearedBy, clearanceMethod: input.clearanceMethod, notes: input.notes });
    }),

  "title.getStatus": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ input }) => {
      return engine.trackTitleExceptions(input.conveyancingMatterId);
    }),

  "title.orderSearch": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string(), titleCompany: z.string().optional() }))
    .mutation(async ({ input }) => {
      return { message: "Title search order functionality coming soon", conveyancingMatterId: input.conveyancingMatterId };
    }),

  // ── Tax ────────────────────────────────────────────────────────────

  "tax.calculateTransfer": publicProcedure
    .input(z.object({ salePrice: z.number(), state: z.string(), county: z.string().optional(), propertyType: z.string().optional() }))
    .query(({ input }) => {
      return engine.calculateTransferTax(input.salePrice, input.state, input.county, input.propertyType);
    }),

  "tax.calculateMortgage": publicProcedure
    .input(z.object({ mortgageAmount: z.number(), state: z.string(), county: z.string().optional() }))
    .query(({ input }) => {
      return engine.calculateMortgageTax(input.mortgageAmount, input.state, input.county);
    }),

  "tax.estimateClosingCosts": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ input }) => {
      return engine.getClosingCosts(input.conveyancingMatterId);
    }),

  // ── Documents ──────────────────────────────────────────────────────

  "documents.generate": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string(), documentType: z.string() }))
    .mutation(async ({ input }) => {
      return engine.generateDocument(input.conveyancingMatterId, input.documentType);
    }),

  "documents.getAvailable": publicProcedure.query(async ({ ctx }) => {
    const config = await ctx.db.conveyancingIntegration.findUnique({ where: { provider: "LCS" } });
    if (config?.isEnabled) return lcs.getAvailableDocuments();
    return { success: true, data: ["DEED", "CLOSING_STATEMENT", "TITLE_REPORT", "TRANSFER_TAX_RETURN", "AFFIDAVIT_OF_TITLE", "MORTGAGE_NOTE", "POWER_OF_ATTORNEY", "BILL_OF_SALE"] };
  }),

  "documents.list": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .query(async ({ ctx, input }) => {
      const matter = await ctx.db.conveyancingMatter.findUniqueOrThrow({ where: { id: input.conveyancingMatterId } });
      const config = await ctx.db.conveyancingIntegration.findUnique({ where: { provider: "LCS" } });
      if (config?.isEnabled && matter.externalMatterId) return lcs.getGeneratedDocuments(matter.externalMatterId);
      return { success: true, data: [] };
    }),

  "documents.generatePackage": publicProcedure
    .input(z.object({ conveyancingMatterId: z.string() }))
    .mutation(async ({ input }) => {
      return engine.generateClosingPackage(input.conveyancingMatterId);
    }),

  // ── Templates ──────────────────────────────────────────────────────

  "templates.list": publicProcedure
    .input(z.object({
      transactionType: z.string().optional(),
      role: z.string().optional(),
      isActive: z.boolean().optional(),
    }).optional())
    .query(async ({ ctx, input }) => {
      return ctx.db.closingChecklistTemplate.findMany({
        where: {
          ...(input?.transactionType && { transactionType: input.transactionType as any }),
          ...(input?.role && { role: input.role as any }),
          ...(input?.isActive !== undefined && { isActive: input.isActive }),
        },
        orderBy: { name: "asc" },
      });
    }),

  "templates.get": publicProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.closingChecklistTemplate.findUniqueOrThrow({ where: { id: input.id } });
    }),

  "templates.create": publicProcedure
    .input(z.object({
      name: z.string(),
      transactionType: z.string(),
      role: z.string(),
      propertyType: z.string().optional(),
      jurisdiction: z.string().optional(),
      items: z.string(),
      isDefault: z.boolean().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingChecklistTemplate.create({ data: input as any });
    }),

  "templates.update": publicProcedure
    .input(z.object({ id: z.string(), data: z.record(z.unknown()) }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingChecklistTemplate.update({ where: { id: input.id }, data: input.data as any });
    }),

  "templates.delete": publicProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.closingChecklistTemplate.update({ where: { id: input.id }, data: { isActive: false } });
    }),

  "templates.initialize": publicProcedure.mutation(async () => {
    return engine.initializeDefaultTemplates();
  }),

  // ── Reports ────────────────────────────────────────────────────────

  "reports.pipeline": publicProcedure.query(async ({ ctx }) => {
    return ctx.db.conveyancingMatter.groupBy({ by: ["status"], _count: { id: true } });
  }),

  "reports.closingCalendar": publicProcedure
    .input(z.object({ from: z.date(), to: z.date() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.conveyancingMatter.findMany({
        where: { closingDate: { gte: input.from, lte: input.to } },
        include: { matter: true },
        orderBy: { closingDate: "asc" },
      });
    }),

  "reports.financialSummary": publicProcedure
    .input(z.object({ from: z.date().optional(), to: z.date().optional() }).optional())
    .query(async ({ ctx, input }) => {
      const where = {
        ...((input?.from || input?.to) && {
          createdAt: { ...(input?.from && { gte: input.from }), ...(input?.to && { lte: input.to }) },
        }),
      };
      const result = await ctx.db.conveyancingMatter.aggregate({ where, _sum: { purchasePrice: true, salePrice: true }, _count: { id: true }, _avg: { purchasePrice: true, salePrice: true } });
      return result;
    }),

  "reports.titleStatus": publicProcedure.query(async ({ ctx }) => {
    const open = await ctx.db.titleException.count({ where: { status: "OPEN" } });
    const inProgress = await ctx.db.titleException.count({ where: { status: "IN_PROGRESS" } });
    const cleared = await ctx.db.titleException.count({ where: { status: "CLEARED" } });
    const total = await ctx.db.titleException.count();
    return { open, inProgress, cleared, total };
  }),

  "reports.checklistProgress": publicProcedure.query(async ({ ctx }) => {
    const checklists = await ctx.db.closingChecklist.findMany({ select: { completedCount: true, totalCount: true } });
    const totalItems = checklists.reduce((s, c) => s + c.totalCount, 0);
    const completedItems = checklists.reduce((s, c) => s + c.completedCount, 0);
    return { totalChecklists: checklists.length, totalItems, completedItems, averagePercentage: totalItems > 0 ? (completedItems / totalItems) * 100 : 0 };
  }),

  "reports.export": publicProcedure
    .input(z.object({ reportType: z.string(), format: z.enum(["pdf", "csv", "xlsx"]).optional() }))
    .query(async ({ input }) => {
      return { message: "Report export functionality coming soon", reportType: input.reportType, format: input.format || "pdf" };
    }),
});
