import type { PracticeAreaConfig } from "./types";

export const PRACTICE_AREA_CONFIGS: PracticeAreaConfig[] = [
  {
    id: "family_law", name: "Family Law", icon: "Heart", description: "Divorce, custody, adoption, and domestic relations",
    matterTemplates: [{ name: "Divorce", description: "Contested or uncontested dissolution of marriage", defaultStatus: "OPEN" }, { name: "Child Custody", description: "Custody and visitation disputes", defaultStatus: "OPEN" }, { name: "Adoption", description: "Domestic and international adoption proceedings", defaultStatus: "OPEN" }, { name: "Prenuptial Agreement", description: "Pre-marital asset protection agreements", defaultStatus: "OPEN" }],
    customFields: [{ name: "Date of Marriage", type: "date", required: true }, { name: "Date of Separation", type: "date", required: false }, { name: "Number of Children", type: "text", required: true, placeholder: "0" }, { name: "Custody Preference", type: "select", required: false, options: ["Sole", "Joint", "Shared", "Undetermined"] }],
    docTemplates: [{ name: "Divorce Retainer Agreement", description: "Standard retainer for divorce representation", category: "retainer" }, { name: "Custody Agreement Template", description: "Parenting plan and custody arrangement", category: "agreement" }, { name: "Separation Agreement", description: "Property and support terms during separation", category: "agreement" }],
    billing: { hourlyRateRange: [250, 400], flatFees: [{ name: "Uncontested Divorce", amount: 2500 }, { name: "Prenuptial Agreement", amount: 1500 }], billingCodes: [{ code: "L110", description: "Fact investigation" }, { code: "L120", description: "Analysis/strategy" }, { code: "L450", description: "ADR/mediation" }], feeType: "hourly" },
    integrations: [{ name: "DocuSign", description: "Electronic signatures for agreements", category: "documents" }, { name: "Zoom", description: "Virtual mediation and client meetings", category: "meetings" }, { name: "QuickBooks", description: "Accounting and trust accounting", category: "billing" }],
    workflows: [{ name: "Divorce Matter", description: "Standard divorce workflow", tasks: [{ title: "Intake call", description: "Initial client consultation", dueDaysFromOpen: 0 }, { title: "Conflict check", description: "Run conflict check on all parties", dueDaysFromOpen: 1 }, { title: "Retainer signed", description: "Execute retainer agreement", dueDaysFromOpen: 3 }, { title: "Gather financial documents", description: "Request tax returns, bank statements, assets", dueDaysFromOpen: 7 }, { title: "File petition", description: "Prepare and file divorce petition", dueDaysFromOpen: 14 }, { title: "Serve spouse", description: "Arrange service of process", dueDaysFromOpen: 21 }, { title: "Discovery", description: "Exchange financial discovery", dueDaysFromOpen: 45 }, { title: "Mediation", description: "Schedule and attend mediation session", dueDaysFromOpen: 75 }, { title: "Final hearing", description: "Prepare for and attend final hearing", dueDaysFromOpen: 120 }] }],
  },
  {
    id: "personal_injury", name: "Personal Injury", icon: "HeartPulse", description: "Auto accidents, slip & fall, medical malpractice",
    matterTemplates: [{ name: "Auto Accident", description: "Motor vehicle collision injury claim", defaultStatus: "OPEN" }, { name: "Slip & Fall", description: "Premises liability injury claim", defaultStatus: "OPEN" }, { name: "Medical Malpractice", description: "Healthcare provider negligence", defaultStatus: "OPEN" }, { name: "Wrongful Death", description: "Death caused by negligence or wrongful act", defaultStatus: "OPEN" }],
    customFields: [{ name: "Date of Incident", type: "date", required: true }, { name: "Injury Description", type: "text", required: true, placeholder: "Describe injuries" }, { name: "Insurance Carrier", type: "text", required: false }, { name: "Treatment Provider", type: "text", required: false }],
    docTemplates: [{ name: "Contingency Fee Agreement", description: "Standard 33%/40% contingency retainer", category: "retainer" }, { name: "Demand Letter", description: "Pre-litigation demand to insurance carrier", category: "letter" }, { name: "HIPAA Release", description: "Authorization to obtain medical records", category: "form" }],
    billing: { hourlyRateRange: [0, 0], flatFees: [], billingCodes: [{ code: "L110", description: "Investigation" }, { code: "L150", description: "Document preparation" }], feeType: "contingency", contingencyPct: 33 },
    integrations: [{ name: "Dropbox", description: "Cloud storage for medical records and evidence", category: "storage" }, { name: "QuickBooks", description: "Track costs and trust accounting", category: "billing" }, { name: "DocuSign", description: "Electronic signatures", category: "documents" }],
    workflows: [{ name: "PI Matter", description: "Standard personal injury workflow", tasks: [{ title: "Intake call", description: "Client intake and case evaluation", dueDaysFromOpen: 0 }, { title: "Sign contingency agreement", description: "Execute fee agreement", dueDaysFromOpen: 1 }, { title: "Request medical records", description: "Send HIPAA releases to providers", dueDaysFromOpen: 3 }, { title: "Investigate liability", description: "Gather police report, witness statements, photos", dueDaysFromOpen: 7 }, { title: "Track treatment", description: "Monitor ongoing medical treatment", dueDaysFromOpen: 30 }, { title: "Send demand letter", description: "Draft and send demand to insurance", dueDaysFromOpen: 90 }, { title: "Negotiate settlement", description: "Negotiate with adjuster", dueDaysFromOpen: 120 }, { title: "File suit if needed", description: "Prepare and file complaint if no settlement", dueDaysFromOpen: 150 }] }],
  },
  {
    id: "criminal_defense", name: "Criminal Defense", icon: "Shield", description: "DUI, felony, misdemeanor, and expungement",
    matterTemplates: [{ name: "DUI/DWI", description: "Driving under the influence defense", defaultStatus: "OPEN" }, { name: "Felony Defense", description: "Serious criminal charge defense", defaultStatus: "OPEN" }, { name: "Misdemeanor", description: "Minor criminal charge defense", defaultStatus: "OPEN" }, { name: "Expungement", description: "Criminal record sealing/expungement", defaultStatus: "OPEN" }],
    customFields: [{ name: "Arrest Date", type: "date", required: true }, { name: "Charges Filed", type: "text", required: true }, { name: "Court Date", type: "date", required: false }, { name: "Bail Amount", type: "currency", required: false }],
    docTemplates: [{ name: "Defense Retainer Agreement", description: "Criminal defense retainer", category: "retainer" }, { name: "Plea Agreement Checklist", description: "Checklist for evaluating plea offers", category: "checklist" }, { name: "Discovery Request", description: "Standard criminal discovery demands", category: "motion" }],
    billing: { hourlyRateRange: [200, 500], flatFees: [{ name: "Misdemeanor Defense", amount: 3000 }, { name: "DUI Defense", amount: 5000 }, { name: "Expungement", amount: 1500 }], billingCodes: [{ code: "L110", description: "Investigation" }, { code: "L230", description: "Trial preparation" }, { code: "L320", description: "Court appearances" }], feeType: "flat" },
    integrations: [{ name: "Docket Alarm", description: "Court docket tracking and alerts", category: "court" }, { name: "Zoom", description: "Client meetings and court hearings", category: "meetings" }, { name: "Dropbox", description: "Secure document storage", category: "storage" }],
    workflows: [{ name: "Criminal Defense Matter", description: "Standard criminal defense workflow", tasks: [{ title: "Intake call", description: "Initial consultation and case review", dueDaysFromOpen: 0 }, { title: "Conflict check", description: "Verify no conflicts of interest", dueDaysFromOpen: 1 }, { title: "Retainer signed", description: "Execute fee agreement", dueDaysFromOpen: 2 }, { title: "Review charges", description: "Analyze charging documents and evidence", dueDaysFromOpen: 3 }, { title: "Request discovery", description: "File discovery demands", dueDaysFromOpen: 7 }, { title: "Research defenses", description: "Legal research on applicable defenses", dueDaysFromOpen: 14 }, { title: "Pretrial motions", description: "File suppression and dismissal motions", dueDaysFromOpen: 30 }, { title: "Trial prep", description: "Witness preparation and exhibits", dueDaysFromOpen: 60 }, { title: "Sentencing", description: "Prepare sentencing memorandum if needed", dueDaysFromOpen: 90 }] }],
  },
  {
    id: "estate_planning", name: "Estate Planning", icon: "Landmark", description: "Wills, trusts, probate, and powers of attorney",
    matterTemplates: [{ name: "Will Drafting", description: "Last will and testament preparation", defaultStatus: "OPEN" }, { name: "Trust Formation", description: "Revocable or irrevocable trust creation", defaultStatus: "OPEN" }, { name: "Probate Administration", description: "Estate administration and probate", defaultStatus: "OPEN" }, { name: "Power of Attorney", description: "Durable POA and healthcare proxy", defaultStatus: "OPEN" }],
    customFields: [{ name: "Date of Birth", type: "date", required: true }, { name: "Beneficiary Names", type: "text", required: false }, { name: "Existing Will", type: "boolean", required: false }, { name: "Estimated Estate Value", type: "currency", required: false }],
    docTemplates: [{ name: "Estate Planning Retainer", description: "Engagement letter for estate planning", category: "retainer" }, { name: "Last Will Template", description: "Standard will template", category: "form" }, { name: "Trust Agreement", description: "Revocable living trust template", category: "agreement" }],
    billing: { hourlyRateRange: [300, 600], flatFees: [{ name: "Simple Will", amount: 500 }, { name: "Living Trust Package", amount: 2500 }, { name: "POA Package", amount: 750 }], billingCodes: [{ code: "L110", description: "Fact gathering" }, { code: "L120", description: "Planning and analysis" }], feeType: "flat" },
    integrations: [{ name: "DocuSign", description: "Remote execution of documents", category: "documents" }, { name: "QuickBooks", description: "Trust and estate accounting", category: "billing" }],
    workflows: [{ name: "Estate Planning Matter", description: "Standard estate planning workflow", tasks: [{ title: "Intake questionnaire", description: "Send asset/family questionnaire", dueDaysFromOpen: 0 }, { title: "Initial consultation", description: "Review goals and family situation", dueDaysFromOpen: 3 }, { title: "Asset inventory", description: "Compile complete asset list", dueDaysFromOpen: 7 }, { title: "Draft documents", description: "Prepare will, trust, POA, healthcare proxy", dueDaysFromOpen: 14 }, { title: "Client review", description: "Review drafts with client", dueDaysFromOpen: 21 }, { title: "Execution ceremony", description: "Sign documents with witnesses/notary", dueDaysFromOpen: 28 }, { title: "Fund trust", description: "Retitle assets into trust", dueDaysFromOpen: 35 }, { title: "Deliver originals", description: "Deliver executed originals to client", dueDaysFromOpen: 42 }] }],
  },
  {
    id: "corporate", name: "Corporate / Business Law", icon: "Building2", description: "Formation, contracts, M&A, compliance",
    matterTemplates: [{ name: "Business Formation", description: "LLC, Corp, or partnership formation", defaultStatus: "OPEN" }, { name: "Contract Review", description: "Commercial contract review and drafting", defaultStatus: "OPEN" }, { name: "M&A Transaction", description: "Merger, acquisition, or sale", defaultStatus: "OPEN" }, { name: "Compliance Review", description: "Regulatory compliance assessment", defaultStatus: "OPEN" }],
    customFields: [{ name: "Entity Type", type: "select", required: true, options: ["LLC", "C-Corp", "S-Corp", "LP", "LLP"] }, { name: "State of Incorporation", type: "text", required: true }, { name: "EIN", type: "text", required: false }, { name: "Fiscal Year End", type: "text", required: false }],
    docTemplates: [{ name: "Corporate Retainer", description: "Outside counsel engagement letter", category: "retainer" }, { name: "NDA Template", description: "Mutual non-disclosure agreement", category: "agreement" }, { name: "Operating Agreement", description: "LLC operating agreement template", category: "agreement" }],
    billing: { hourlyRateRange: [350, 700], flatFees: [{ name: "LLC Formation", amount: 1500 }, { name: "NDA Review", amount: 500 }], billingCodes: [{ code: "L110", description: "Investigation" }, { code: "L200", description: "Drafting" }, { code: "L300", description: "Negotiation" }, { code: "L400", description: "Due diligence" }], feeType: "hourly" },
    integrations: [{ name: "DocuSign", description: "Contract execution", category: "documents" }, { name: "Slack", description: "Team communication", category: "communication" }],
    workflows: [{ name: "Business Formation", description: "Standard formation workflow", tasks: [{ title: "Intake and entity selection", description: "Determine entity type and structure", dueDaysFromOpen: 0 }, { title: "Name availability search", description: "Check state registry for name availability", dueDaysFromOpen: 1 }, { title: "Draft formation documents", description: "Prepare articles/certificate", dueDaysFromOpen: 3 }, { title: "File with state", description: "Submit formation documents", dueDaysFromOpen: 5 }, { title: "Obtain EIN", description: "Apply for federal tax ID", dueDaysFromOpen: 7 }, { title: "Draft governing documents", description: "Operating agreement or bylaws", dueDaysFromOpen: 10 }, { title: "Initial resolutions", description: "Prepare organizational resolutions", dueDaysFromOpen: 14 }, { title: "Deliver package", description: "Deliver completed formation package", dueDaysFromOpen: 21 }] }],
  },
  {
    id: "immigration", name: "Immigration", icon: "Globe", description: "Visas, green cards, citizenship, deportation defense",
    matterTemplates: [{ name: "Visa Application", description: "Work, family, or investment visa", defaultStatus: "OPEN" }, { name: "Green Card", description: "Permanent residence application", defaultStatus: "OPEN" }, { name: "Citizenship", description: "Naturalization application", defaultStatus: "OPEN" }, { name: "Deportation Defense", description: "Removal proceeding defense", defaultStatus: "OPEN" }],
    customFields: [{ name: "Country of Origin", type: "text", required: true }, { name: "Visa Type", type: "select", required: false, options: ["H-1B", "L-1", "O-1", "EB-1", "EB-2", "EB-3", "F-1", "Other"] }, { name: "Entry Date", type: "date", required: false }, { name: "Prior Applications", type: "boolean", required: false }],
    docTemplates: [{ name: "Immigration Retainer", description: "Engagement for immigration representation", category: "retainer" }, { name: "G-28 Cover Letter", description: "Notice of entry of appearance cover", category: "letter" }, { name: "RFE Response Template", description: "Template for USCIS RFE response", category: "letter" }],
    billing: { hourlyRateRange: [150, 400], flatFees: [{ name: "H-1B Petition", amount: 3000 }, { name: "Green Card (EB)", amount: 5000 }, { name: "Naturalization", amount: 1500 }], billingCodes: [{ code: "L110", description: "Case preparation" }, { code: "L120", description: "Form preparation" }], feeType: "flat" },
    integrations: [{ name: "DocuSign", description: "Remote document signing", category: "documents" }, { name: "Dropbox", description: "Client document collection", category: "storage" }],
    workflows: [{ name: "Visa Application", description: "Standard visa workflow", tasks: [{ title: "Intake and eligibility review", description: "Assess visa eligibility", dueDaysFromOpen: 0 }, { title: "Collect documents", description: "Gather supporting documents", dueDaysFromOpen: 7 }, { title: "Prepare petition", description: "Complete USCIS forms", dueDaysFromOpen: 14 }, { title: "Client review", description: "Review petition with client", dueDaysFromOpen: 21 }, { title: "File petition", description: "Submit to USCIS", dueDaysFromOpen: 28 }, { title: "Monitor status", description: "Track case status online", dueDaysFromOpen: 60 }, { title: "RFE response (if issued)", description: "Respond to any evidence requests", dueDaysFromOpen: 90 }, { title: "Case resolution", description: "Approval notification and next steps", dueDaysFromOpen: 180 }] }],
  },
  {
    id: "real_estate", name: "Real Estate", icon: "Home", description: "Closings, leases, title disputes, and zoning",
    matterTemplates: [{ name: "Purchase/Sale", description: "Residential or commercial transaction", defaultStatus: "OPEN" }, { name: "Lease Review", description: "Commercial or residential lease", defaultStatus: "OPEN" }, { name: "Title Dispute", description: "Title defect or boundary dispute", defaultStatus: "OPEN" }, { name: "Zoning", description: "Variance or rezoning application", defaultStatus: "OPEN" }],
    customFields: [{ name: "Property Address", type: "text", required: true }, { name: "Purchase Price", type: "currency", required: false }, { name: "Closing Date", type: "date", required: false }, { name: "Lender Name", type: "text", required: false }],
    docTemplates: [{ name: "Real Estate Retainer", description: "Engagement for real estate transaction", category: "retainer" }, { name: "Title Review Letter", description: "Title examination summary letter", category: "letter" }, { name: "Lease Review Checklist", description: "Key terms checklist for lease review", category: "checklist" }],
    billing: { hourlyRateRange: [200, 450], flatFees: [{ name: "Residential Closing", amount: 1500 }, { name: "Lease Review", amount: 750 }], billingCodes: [{ code: "L110", description: "Due diligence" }, { code: "L120", description: "Document review" }, { code: "L430", description: "Closing attendance" }], feeType: "flat" },
    integrations: [{ name: "DocuSign", description: "Remote closings", category: "documents" }, { name: "QuickBooks", description: "Escrow and trust accounting", category: "billing" }],
    workflows: [{ name: "Real Estate Closing", description: "Standard closing workflow", tasks: [{ title: "Contract review", description: "Review purchase/sale agreement", dueDaysFromOpen: 0 }, { title: "Title search", description: "Order and review title search", dueDaysFromOpen: 3 }, { title: "Review exceptions", description: "Analyze title exceptions", dueDaysFromOpen: 7 }, { title: "Due diligence", description: "Inspections, surveys, environmental", dueDaysFromOpen: 14 }, { title: "Mortgage coordination", description: "Coordinate with lender", dueDaysFromOpen: 21 }, { title: "Prepare closing docs", description: "Draft deed, closing statement", dueDaysFromOpen: 28 }, { title: "Pre-closing review", description: "Final walkthrough and document review", dueDaysFromOpen: 29 }, { title: "Closing", description: "Attend closing, record deed", dueDaysFromOpen: 30 }] }],
  },
  {
    id: "bankruptcy", name: "Bankruptcy", icon: "Scale", description: "Chapter 7, 13, 11, and creditor negotiations",
    matterTemplates: [{ name: "Chapter 7", description: "Liquidation bankruptcy", defaultStatus: "OPEN" }, { name: "Chapter 13", description: "Reorganization with repayment plan", defaultStatus: "OPEN" }, { name: "Chapter 11", description: "Business reorganization", defaultStatus: "OPEN" }, { name: "Creditor Negotiation", description: "Pre-filing debt negotiation", defaultStatus: "OPEN" }],
    customFields: [{ name: "Filing Type", type: "select", required: true, options: ["Chapter 7", "Chapter 13", "Chapter 11"] }, { name: "Total Debt", type: "currency", required: true }, { name: "Monthly Income", type: "currency", required: true }, { name: "Prior Filings", type: "boolean", required: false }],
    docTemplates: [{ name: "Bankruptcy Retainer", description: "Engagement for bankruptcy representation", category: "retainer" }, { name: "Chapter 7 Checklist", description: "Document gathering checklist", category: "checklist" }, { name: "Means Test Worksheet", description: "Income and expense analysis", category: "form" }],
    billing: { hourlyRateRange: [200, 350], flatFees: [{ name: "Chapter 7 Filing", amount: 1500 }, { name: "Chapter 13 Filing", amount: 3500 }], billingCodes: [{ code: "L110", description: "Case preparation" }, { code: "L120", description: "Petition preparation" }, { code: "L160", description: "341 meeting attendance" }], feeType: "flat" },
    integrations: [{ name: "DocuSign", description: "Petition signatures", category: "documents" }, { name: "QuickBooks", description: "Financial analysis", category: "billing" }],
    workflows: [{ name: "Chapter 7 Filing", description: "Standard Chapter 7 workflow", tasks: [{ title: "Intake and means test", description: "Evaluate eligibility", dueDaysFromOpen: 0 }, { title: "Credit counseling", description: "Complete required credit counseling", dueDaysFromOpen: 3 }, { title: "Gather documents", description: "Tax returns, pay stubs, bank statements", dueDaysFromOpen: 7 }, { title: "Prepare petition", description: "Complete bankruptcy schedules", dueDaysFromOpen: 14 }, { title: "Client review", description: "Review petition with client", dueDaysFromOpen: 18 }, { title: "File petition", description: "File with bankruptcy court", dueDaysFromOpen: 21 }, { title: "341 meeting prep", description: "Prepare client for trustee meeting", dueDaysFromOpen: 45 }, { title: "Discharge", description: "Receive discharge order", dueDaysFromOpen: 120 }] }],
  },
];

export function getConfigByArea(area: string): PracticeAreaConfig | undefined {
  return PRACTICE_AREA_CONFIGS.find((c) => c.id === area);
}
